apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  SECRET_KEY: ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # base64 encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password" 