apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
data:
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/devops_app"
  FLASK_ENV: "production"
  REACT_APP_API_URL: "http://backend-service:5000/api" 